Develop
Pi4yka/PetCalc pull request #1
Opened 2023-01-22 13:12 UTC by Pi4yka

пишем ему в тг+вк+почта+ватсапп чтобы он провел код ревью

2023-01-22 16:15 UTC, qSonic commented on app/src/main/java/com/example/petcalc/MainActivity.kt
> +// Написать ридми на гитхаб, 2 скриншота
сам удаляй

2023-01-22 16:18 UTC, qSonic commented on app/src/main/java/com/example/petcalc/MainActivity.kt
> +    private lateinit var MainActivityBinding: ActivityMainBinding
переменные пишем с маленькой буквы

2023-01-22 16:26 UTC, qSonic commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.AppCompat.DayNight.NoActionBar"
Заюзать свою тему! Унаследоваться от той что сейчас указана в манифесте

2023-01-22 16:28 UTC, qSonic commented on app/src/main/res/drawable/custom_button.xml
> +
лишний пробел

2023-01-22 16:29 UTC, qSonic commented on app/src/main/res/drawable/custom_result.xml
> +
лишний пробел

2023-01-22 16:34 UTC, qSonic commented on app/src/main/res/drawable/custom_input.xml
> +<?xml version="1.0" encoding="utf-8"?>
Перемеиновать все background элементы

2023-01-22 16:40 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +        android:id="@+id/linearLayout"
нет, не линеаар, и даже не релатив. поставь контрейнт, назови headerContainer

2023-01-22 16:41 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +    <RelativeLayout
выпиолить релатив

2023-01-22 16:41 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +        android:id="@+id/relativeResultBlock"
резалтКонтейнекр

2023-01-22 16:44 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            tools:layout_editor_absoluteY="190dp" />
убрать

2023-01-22 16:45 UTC, qSonic commented on app/src/main/res/values/strings.xml
>      <string name="size_title">Size your pet</string>
Your pet's size будет лучше

2023-01-22 16:46 UTC, qSonic commented on app/src/main/res/values/strings.xml
>      <string name="first_fragment_title">First Fragment</string>
удалить

2023-01-22 16:50 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            android:src="@drawable/dog"
убрать из v24

2023-01-22 17:10 UTC, qSonic requested changes

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            android:layout_marginTop="16dp"
вынести маргин 16

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +        android:id="@+id/relativeResultBlock"
кстати с контрейнтами что то не так)

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +
пробелы

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +
в конце работы над файлом, нажимай CTRL + ALT + L

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +
лишняя строка

2023-01-22 17:10 UTC, qSonic commented on app/src/main/java/com/example/petcalc/screen/first/CalculatorFragment.kt
>                  .isNotEmpty()
вынести проверку полей в приватный метод isInputsEmpty

2023-01-22 17:10 UTC, qSonic commented on app/src/main/java/com/example/petcalc/screen/first/CalculatorFragmentViewModel.kt
>      fun getSize(
функция которая ничего не возвращает не может называться get*

2023-01-22 17:10 UTC, qSonic commented on app/src/main/java/com/example/petcalc/screen/first/CalculatorFragmentViewModel.kt
> +                else -> "Error"
Вынести все строки в ресурсы

2023-01-22 17:10 UTC, qSonic commented on app/src/main/java/com/example/petcalc/screen/first/CalculatorFragmentViewModel.kt
>          MutableLiveData<String>()
обзервить не String а ResId

2023-01-22 17:10 UTC, qSonic commented on app/src/main/java/com/example/petcalc/screen/first/CalculatorFragment.kt
>          Log.d("TEST", "Fragment created")
удалить

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            tools:layout_editor_absoluteY="190dp" />
убрать

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            tools:layout_editor_absoluteY="190dp" />
убрать

2023-01-22 17:10 UTC, qSonic commented on app/src/main/res/layout/fragment_calculator.xml
> +            tools:layout_editor_absoluteY="190dp" />
убрать

2023-01-22 20:06 UTC, Pi4yka commented on app/src/main/java/com/example/petcalc/MainActivity.kt
> +// Написать ридми на гитхаб, 2 скриншота
удалил

2023-01-22 20:08 UTC, Pi4yka commented on app/src/main/java/com/example/petcalc/MainActivity.kt
> +    private lateinit var MainActivityBinding: ActivityMainBinding
фиксанул

2023-01-22 20:13 UTC, Pi4yka commented on app/src/main/res/drawable/custom_button.xml
> +
фикс

2023-01-26 16:07 UTC, qSonic approved these changes
ВСе хорошо!

2023-01-26 16:07 UTC, merged